version: "3"

services:
  ipfs:
    image: ipfs/go-ipfs:v0.14.0
    ports:
      - "5001:5001"
    volumes:
      - ./data/ipfs:/data/ipfs

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
      LANG: C
      LC_ALL: C

    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - lc_collate=C
      - -c
      - lc_ctype=C

  graph-node:
    image: graphprotocol/graph-node:v0.33.0
    depends_on:
      - postgres
      - ipfs
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://host.docker.internal:8545"
      RUST_LOG: info
    ports:
      - "8000:8000"  # GraphQL endpoint
      - "8020:8020"  # Admin / deploy endpoint
      - "8030:8030"  # Prometheus
